eternnoir/pyTelegramBotAPI

- telebot/__init__.py
Reverts eternnoir/pyTelegramBotAPI#9
> Revert "...actually implemented the offset in TeleBot#get_update now..."

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_types.py
Implemented the offset parameter for the getUpdates API call according to https://core.telegram.org/bots/api#getupdates
In short: the offset is calculated by adding 1 to the id of the last received Update.
Caching messages in a list is now redundant, so the cache is removed. Only the id of the last received Update is kept for future getUpdates calls.
Also did some code clean-up.
> Implemented the offset parameter.

- README.md
- setup.py
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_types.py
Changed apihelper#convert_markup
Constructed the Jsonable abstract class. All subclasses must override Jsonable#to_json.
Added ForceReply
Made ReplyKeyboardHide, ReplyKeyboardMarkup and ForceReply a subclass of Jsonable to make things less complicated in convert_markup.
Fixed unnecessary Thread creation when no new messages arrived.
Implemented getUserProfilePhotos.
> Implemented #17 (with some small adjustments) and ForceReply

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_types.py
Created _make_request and removed check_result in apihelper.py for efficiency and consistency improvements.
Created JsonSerializable (previously Jsonable) and JsonDeserializable.
All relevant classes now subclass JsonDeserializable to eliminate unneeded json -> string -> json conversions.
Added a message_handler decorator. It's pretty cool and useful. An example:
```python
bot = TeleBot('TOKEN')
@bot.message_handler(regexp='(/start|/?help)')
def command_help(message):
bot.send_message(message.chat.id, 'Did someone call for help?')
@bot.message_handler(func=lambda message: message.document.mime_type == 'text/plain', content_types=['document'])
def command_handle_document(message):
bot.send_message(message.chat.id, 'Document received, sir!')
@bot.message_handler(func=lambda message: True, …
```
> Some new features and minor improvements.

- telebot/__init__.py
Function would previously incorrectly slice /command@BotName.
> Fix TeleBot#extract_command

- examples/detailed_example/detailed_example.py
Now using message handlers instead of the listener for almost everything (except console output)
> Updated detailed example to use message handlers

- telebot/__init__.py
`threading.Event`s have a built in wait function which allows the while loop to wait based on whether the `Event` is set to true or the timer runs out. Without this commit, the thread simply hangs when `time.sleep(interval)` is called.
> Changed __stop_polling from bool to threading.Event().

- telebot/__init__.py
- telebot/apihelper.py
- tests/test_telebot.py
Would this be a useful addition to the API?
It's pretty easy to use, the only caveat is that the a message must be sent with ForceReply in order to correctly identify a reply to this message.
> Implements #26

- setup.py
- telebot/apihelper.py
- tests/test_telebot.py
I tried to provide a better error description. Warning: this is untested code (because I have no idea how to manually create an HTTP 403)
> Better error description

- examples/telebot_bot/telebot_bot.py
A slight change, still not very good though. Something like `{!s}{!s}{!s}.format(....)` seems a better aproach
> Check if field is None

- telebot/__init__.py
- telebot/apihelper.py
See https://core.telegram.org/bots/api#sendmessage
> Implement parse_mode

- README.md
- examples/download_file_example.py
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_telebot.py
+ download_file in TeleBot, for convenience. Still needs documentation though!
> Add getFile method and File type

- telebot/__init__.py
Here is a race-condition in current code.
If `command A` registers `for_reply a`, and `for_reply a` registers `for_reply b`, then `for_reply b` will be wrongly deleted from the list and never be triggered.
Because before `for_reply a` is called, `for_reply a` is located in the first position of `message_subscribers_callbacks`, but after `for_reply a` accomplishes, when `for_reply b` is registered, `for_reply b` is located in the first place and `for_reply a` is located in the second one.
The `for_reply b` is wrongly deleted and `for_reply a` is left.
There are two methods to resolve this problem:
1. Reserve the `message_subscribers_callbacks` and the `message_subscribers_messages`. As a result, the position of `for_reply a` will not change during the process. But considering that when …
> fix race-condition for register_for_reply

- telebot/types.py
* dict.get(key) returns None if key is not in the dictionary
* used the class method's class reference to instantiate type classes
> Little code cleanup

- telebot/__init__.py
Sometimes a bot only makes sense in a real-time situation where updates received while it was offline should be discarded.
Added the skip_pending param to telebot constructor to be able to get and discard all pending updates sent before the first poll of the bot.
> Get and discard all pending updates sent before first poll of the bot

- telebot/__init__.py
partially fixes #112.  other part is on cherrypy's side: gist needs to be updated after this PR merged.
> __retrieve_updates split into process_new_updates

- telebot/__init__.py
Added setters for message/inline/chosen-inline handlers. This is may be helpful if you don't want to use decorators by some reason.
> Added setters for message/inline/chosen-inline handlers.

- telebot/util.py
Added method for extracting arguments from commands using regexp
> extract_argument

- examples/bot20-pass_generator-example.py
**Methods that was used:**
- InlineKeyboardMarkup()
- InlineKeyboardButton("", callback_data="...")
- callback_query_handler()
- edit_message_text(t)
- answer_callback_query()
> bot20 example - password or pin generator bot

- telebot/types.py
* Added the field `emoji` to the `Sticker` object. Your bot can now know the emoji a sticker corresponds to.
* Added the field `forward_from_chat` to the `Message` object for messages forwarded from channels.
> Added 06.05.16 updates

- telebot/telebot_class.py
last_update_id should be int not update instance.
And fix yeild updates.
> Fix last_update_id is int. Fix yeild updates.

- README.md
Also added description of urlprobot and lmgtfy_bot
> Added Send2KindleBot

- telebot/__init__.py
+ More flexibility for different handlers(callback_query_handler and etc.): now they are not limited in input arguments so can be easily extended by subclassing
> + More flexibility for different handlers(callback_query_handler and etc.)

- examples/inline_example.py
> Example of inline bot fixed

- telebot/__init__.py
branch changed to master
#232 - develop was here
> return statement added to callback_query_handler in decorator

- telebot/types.py
InlineQueryResultAudio, InlineQueryResultVoice, InlineQueryResultCachedAudio, InlineQueryResultCachedVoice
> Added caption field to several objects

- telebot/apihelper.py
1. https://core.telegram.org/bots/api#setgamescore
2. https://core.telegram.org/bots/api#getgamehighscores
> Added setGameScore and getGameHighScores

- telebot/apihelper.py
- telebot/types.py
Telegram is going to release November Bot API updates. Here're some new things found
> Bot API November updates

- telebot/types.py
All explanation is here https://github.com/eternnoir/pyTelegramBotAPI/issues/265
> Added isinstance for bytes to function 'add' in ReplyKeyboardMarkup

- telebot/apihelper.py
Telegram doesn't accept rfc2231 styled filename. Using utf-8 directly.
> Non-ASCII chars for filename.

- telebot/__init__.py
Added re.IGNORECASE flag to message_handler, so it matches without chars case.
> Added IGNORECASE flag to message_handler

- telebot/apihelper.py
#284 creates bug of too much recursions
> RecursionError fix during sending files

- telebot/__init__.py
In the old version you can change the number of threads only from 1 to 2, now you can change it in any ranges.
> Add more accurate control over threads count

- telebot/types.py
I just added language code for users (Maybe you prefer a pull request with all new changes xD but that one is the most important for my bot)
> Added language code for users

- README.md
- setup.py
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
Just apihelper.py methods, need more work
> Payments methods

- examples/webhook_examples/webhook_cherrypy_echo_bot.py
Added option to disable CherryPy logging to `examples/webhook_examples/webhook_cherrypy_echo_bot.py`
> Added option to disable CherryPy logging

- examples/download_file_example.py
Fixed missing binary flag for `open`.
> Added file opening mode

- README.md
Add info and example about using some content types in one function.
> Using some content types in one function

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
All features for Bot API v3.1 are done.
No tests provided (though I've tested the lib more or less, all methods and fields seem to be working)
> Bot API v3.1

- telebot/util.py
If some exception occure, bot will just show message 'Exception occurred', which is not informative at all and sometimes makes finding mistake pretty hard thing. Based on this suggestion https://github.com/eternnoir/pyTelegramBotAPI/issues/280, i create pull request with needed module (traceback) imported.
> Informative exception message for better exception handling

- telebot/types.py
- Added the new field pinned_message to the Chat object.
- Added the new fields author_signature and forward_signature to the Message object.
- Added the new field is_bot to the User object.
> Bot API 3.3

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
Please, everyone, review this PR, it might contain mistakes and I might skip something (no tests were edited btw)
> Bot API 3.4: new methods for live locations, new objects.

- README.md
> Added SmartySBot to README

- telebot/__init__.py
https://core.telegram.org/bots/api#addstickertoset
> Fix optional parameter

- examples/webhook_examples/webhook_flask_heroku_echo.py
Hello,
I tried to deploy my bot to the production recently. But I got few errors.
1) **Address already in use** 
To solve this issue you need to encapsulate running a server (`if __name__ ...`);
2) **Port is not an integer value**
To solve you need to wrap a getting the port from the environment to `int`.
3) Also bot didn't work without fixing the `URLs`. 
Fix it in the following style as my patch.
> Make the Heroku example actual

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
-- Added 'json' property to class 'Message', to quickly save a message to the database
-- Added bot.get_file_url method
> Minor improvements

- telebot/__init__.py
- telebot/types.py
-- Added 'html_text' property to class 'Message' to parse message entity.
-- Added method 'infinity_polling' to class 'TeleBot' to ignore all exceptions. (#473, #474)
> Bugfixes and minor improvements

- README.md
Updated and 100% working info in SOCKS5 proxy block.
> Update README.md SOCKS5 proxy info

- telebot/types.py
html_text now works with text_link
html_caption now works for caption/caption_entities
> html_text fix and html_caption

- .travis.yml
- telebot/__init__.py
- telebot/util.py
fix in Python 3.7
issues:  https://github.com/eternnoir/pyTelegramBotAPI/issues/524
> rename async -> async_dec

- telebot/types.py
fixed https://github.com/eternnoir/pyTelegramBotAPI/issues/550
> Added parse mode for objects in Inline mode

- telebot/__init__.py
I am fix issue "When you use threading mode - deepcopy crash bot #555"
> Fix issue When you use threading mode

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_telebot.py
First item in https://github.com/eternnoir/pyTelegramBotAPI/issues/542
Currently only with string thumb (url or file_id). Also added test for editMessageMedia.
-- Added support for editing the media content of messages: added the method editMessageMedia and new types InputMediaAnimation, InputMediaAudio, and InputMediaDocument.
> v.4.0: InputMediaAnimation, InputMediaAudio, InputMediaDocument, editMessageMedia

- telebot/types.py
https://travis-ci.org/eternnoir/pyTelegramBotAPI/jobs/415510393
> fix: support python2 super()

- telebot/types.py
> fix: python2 positional argument specifiers

- telebot/apihelper.py
- telebot/util.py
Very necessary for proxy changing and other reconnection stuff
> Reset requests.Session feature

- README.md
Updating the section with "Bots using this API" in README.md
> added creationdatebot to bots api list

- README.md
Remove areajugonesbot; add vigobustelegrambot
> update bot list

- telebot/types.py
`passport_data` content type added
> New content type related to Telegram Passport

- telebot/types.py
https://core.telegram.org/bots/api#message
> create field forward_from_message_id in Message

- README.md
Change in README.md chatid to chat_id to be the same as other examples
> Change chatid to chat_id to be the same as other examples

- telebot/apihelper.py
Merge Fixes [# 684](https://github.com/eternnoir/pyTelegramBotAPI/pull/684)
> Update apihelper.py #2

- examples/serverless/azure_functions
Simple echo bot using Azure Functions as webhook.
> Using Azure Functions for serverless bots.

- telebot/types.py
I added animation type to recognize gifs
> Added Animation

- examples/detailed_example/detailed_example.py
- setup.py
- telebot/__init__.py
Significant design updated from
https://github.com/eternnoir/pyTelegramBotAPI/pull/711
> Design updates from #711

- README.md
> Added missed bracket

- telebot/types.py
Cannot find "is_anonymous" flag in Poll object, so I add it. My first pull request, hope I'm doing it right 👀
> Add is_anonymous flag to Poll type

- README.md
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
> Fix missing padding space in code sample comments in README

- README.md
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
> Use proper language for * query mentions in README

- README.md
> Add new bot in README

- examples/middleware/i18n.py
- examples/middleware/session.py
- telebot/__init__.py
- telebot/apihelper.py
- tests/test_telebot.py
Closes #781 
This is my initial implementation for Adding Middleware feature. Thus, any comments or ideas are welcome to discuss here.
I hope this feature will help most of the developers to implement different kind of middleware capabilites starting from session creation to localization.
> Add Middleware Handler 

- README.md
Update README with Middleware Handler description
> Middleware Handler README Update

- README.md
- telebot/types.py
Refactoring.
new_chat_member is out of support.
Bugfix in html_text.
Started Bot API conformance checking.
> Refactoring and API conformance

- requirements.txt
- setup.py
- telebot/__init__.py
- telebot/handler_backends.py
- tests/test_handler_backends.py
Here are some bigger changes to the codebase, however backward compatability is kept, only private methods or attributes have been involved in refactoring, all the public methods are kept safely.
- `HandlerBackend` Mechanism for storing handlers
- `MemoryHandlerBackend` (by default is being used for backward compatability)
- `FileHandlerBackend` (by default is being used instead of `Saver` class for backward compatibility)
- `RedisHandlerBackend`
- `next_step_backend` attribute of the `Telebot` (instead of `next_step_handlers`)
- `reply_backend` attribute of the `Telebot` (instead of `reply_handlers`)
- All backends are covered with tests
-  `_notify_next_handlers` method of Telebot has been changed for better readibility
- `_notify_reply_handlers` method of Telebot has been changed for …
> Codebase Refactoring and HandlerBackend Mechanism Implementation

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_types.py
Polls are updated to the latest API state.
Minor code refactoring.
> Polls are updated to the latest API state

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_telebot.py
- tests/test_types.py
> update dice as the api has updated

- telebot/__init__.py
- telebot/handler_backends.py
- tests/test_handler_backends.py
> Remove type hinting

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/util.py
If you already start using send_poll - please, revise the code.
> send_poll revised to standart signature

- .gitignore
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
Hello. I would like to add a new data type and method. Perhaps there are errors. Ready for comments.
> UPG: Add BotCommand, setMyCommands

- telebot/__init__.py
- telebot/types.py
- tests/test_types.py
+ add PollAnswer, poll_answer_handler
+ make User Serializable and Dictionaryble
+ some pep fixes
> add PollAnswer, poll_answer_handler

- telebot/types.py
Sorry, this is my first time I create pull request and probably I made lot of things wrong.
Added:
can_join_groups
can_read_all_group_messages
supports_inline_queries
> Update User type

- telebot/__init__.py
- telebot/apihelper.py
Added the possibility to send thumbnails with send_audio and send_video
> Added thumbnail support for send_audio and send_video

- telebot/__init__.py
- telebot/util.py
In functions
send_message
send_photo
send_voice
send_document
send_video
send_animation
edit_message_text
edit_message_caption
> Added ability to set parse_mode by default

- telebot/__init__.py
- telebot/apihelper.py
Just added ability to specify params of width and height for video
> No width/height parameters for send_video method

- telebot/apihelper.py
Added RETRY_ON_ERROR var. If its value is true, we'll try to get proper result MAX_RETRIES times, with RETRY_TIMEOUT delay between requests. Last request will be called outside of the try block, so it will throw an exception on failure
P.S.
I'm actually not sure if there are better ways to solve this problem, but this was my way of solving it
> Retry on requests error

- telebot/apihelper.py
- telebot/util.py
Added autoconversion of PIL image to file-like object. PIL module is optional
>  Support for PIL images as photo argument

- telebot/apihelper.py
- telebot/types.py
Bugfix and DISABLE_KEYLEN_ERROR to supress keyboard length errors.
> Bugfix and DISABLE_KEYLEN_ERROR

- README.md
TasksListsBot
MyElizaPsychologistBot
> Append bots to list

- requirements.txt
- setup.py
- telebot/__init__.py
- telebot/apihelper.py
- telebot/handler_backends.py
- telebot/types.py
- telebot/util.py
- telebot/version.py
Empty list optimization: None instead of [].
Py2 arteacts removed: no more six moudle used.
> Empty list optimization, Py2 arteacts removed

- README.md
I've made a weather forecast bot using your API. Can you approve my request to add it, please?
> Added Frcstbot description

- telebot/__init__.py
- telebot/apihelper.py
+ add unpin_all_chat_messages() (former unpin_chat_message())
* update unpin_chat_message() (add message_id arg)
> Bot API 5.0 pinning-unpinning logic update

- telebot/__init__.py
Allow parse_mode = "" to disable default parse mode.
> parse_mode = ""

- examples/webhook_examples/README.md
- examples/webhook_examples/webhook_twisted_echo_bot.py
I was integrating my bot with Twisted and figured I could wrap a minimal example and post a PR. Tell me if anything needs fixing. Tested on Arch VPS with latest python (3.9) and libraries from pip
> Add webhook example for Twisted

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
Bot API conformance up to 4.4
Added webhook parameters from 5.0
> Bot API update

- README.md
I had a few problems while developing my first bot based on this library, these additions would have helped me and might do so for future generations. It's "paying it forward" so to say.
> Extend readme with more usage hints

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_telebot.py
> Added copyMessage method

- README.md
Add another bot to the list below
> README list of bots update

- README.md
> Added Price Tracker bot

- telebot/types.py
- tests/test_types.py
I thought that this is useful.
> New property full_name

- telebot/types.py
Well, now it is compatible with python3.5
> Change fstrings to string formatting

- README.md
> Add Torrent Hunt bot in README

- telebot/apihelper.py
- telebot/types.py
Now send_poll correctly operates with PollOptions passed as array of PollOption.
> send_poll fix with PollOptions

- telebot/version.py
Regular release with minor updates
> Release 3.7.8

- telebot/apihelper.py
Previous update was inconsistent, sorry.
> send_poll fix of fix

- telebot/__init__.py
- telebot/apihelper.py
Implemented following methods:
* https://core.telegram.org/bots/api#editchatinvitelink
* https://core.telegram.org/bots/api#revokechatinvitelink
* https://core.telegram.org/bots/api#createchatinvitelink
> Create_chat_invite_link, edit_chat_invite_link, revoke_chat_invite_link methods

- telebot/__init__.py
fixed wrong ordered argument error on calling apihelper.set_game_score method in set_game_score
> Bug fixed on set_game_score

- telebot/util.py
Added the function `smart_split` to split text into more meaningful parts.
> Add `smart_split` function to utils.py

- telebot/util.py
- Added function `escape`
- Added function `user_link`
- Added function `quick_markup`
- Added some type hints
> Added some functions and type hints

- .github/workflows/setup_python.yml
Github actions implementation, to build on each PR :)
Same as .travis.yml setup but with Github Actions https://github.com/eternnoir/pyTelegramBotAPI/actions
```yml
on:  # Triggers the workflow on push or pull request events but only for the master branch  
push:
branches: [ master ]  
pull_request:
branches: [ master ]
```
> Github Actions: setup for 3.6+ pypy3.6+

- .gitignore
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- telebot/util.py
So, now i testet everything usin pytest and python versions 3.6-3.9 on macOS.
I hope this is now acceptable. Sorry again for my mistakes, I'm pretty new on GitHub.
Here the output from my tests:
```
fredi@fredis-Hackintosh pyTelegramBotAPI % /usr/local/bin/python3.6 -m pytest
============================================== test session starts ===============================================
platform darwin -- Python 3.6.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/fredi/Documents/GitHub/pyTelegramBotAPI
collected 98 items                                                                                               
tests/test_handler_backends.py .......ss                                                                   [  9%]
tests/test_telebot.py …
```
> Fixed the errors from my last PRs

- telebot/types.py
- tests/test_handler_backends.py
- tests/test_telebot.py
- tests/test_types.py
* Added class `ChatMemberUpdated` to `types.py`
* Simplified `de_json` functions in `WebhookInfo` and `Update` classes (for overall more consistent code)
* changed `options_ids` to `option_ids` in class `PollAnswer`
* Added test for `ChatMemberUpdated` class in `test_types.py` and added the fields `my_chat_member` and `chat_member` to `Update` class and its tests
My last PR for today, i promise ^^
> Added class ChatMemberUpdated

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- telebot/util.py
* Added some missing classes, functions and variables from TelegramBotAPI 4.5-5.2 to pyTelegramBotAPI
* Added type hints for (almost) all TeleBot functions
> Added some missing features

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
* Added InputInvoiceMessageContent
* Added tgs_sticker support 
* changed Union[Type, None] type hints to Optional[Type]
(that's it for today :D )
> added InputInvoiceMessageContent and tgs_sticker support

- telebot/__init__.py
- telebot/types.py
- telebot/util.py
I know, no more updates for now, but i think this small addition was needed.
I hope this is ok for you :)
> Added handlers for `my_chat_member` and `chat_member`

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_telebot.py
second try)
- Personalized Commands for different chats
- Custom Placeholders of input field for ReplyKeyboardMarkup and ForceReply.
#1203
> 2 of 3 Bot API 5.3 changes

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
added the new function names (the previous names are still working) from 5.3 and some other small changes
> new 5.3 function names

- README.md
* Added the new message_handlers
* Added some information about local Bot API Server
* Replaced the split_string with the smart_split function
> Just a small README update

- telebot/util.py
- tests/test_telebot.py
I think this could be useful in the future :) 
Or should we replace the old deprecated decorator?
what du you think?
> new deprecated decorator

- telebot/types.py
This is a better representation of the changes of a chat member.
needs less if else stuff later IMO
> Added the property `difference` to the class ChatMemberUpdated 

- README.md
This is a small project that's been humming along for a few years, that depends on this library. Now that I've recently cleaned up the repo structure and "infrastructure" parts, I think it's appropriate for listing here. Thanks!
> mention colorcodebot as a project using this library

- telebot/__init__.py
> Fix wrong type hint

- telebot/__init__.py
- telebot/apihelper.py
https://github.com/eternnoir/pyTelegramBotAPI/issues/1247
> caption_entities in edit_message_caption

- README.md
Listed oneIPO bot created using pyTelegramBotAPI in  section : Bots using this API
> Add IPO bot

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
Check and update for full compatibility to Bot API up to 5.0
> Check and update for full compatibility to Bot API up to 5.0

- telebot/util.py
> A Google Cloud Functions webhook

- telebot/util.py
"animation" was missing in content_types
> Added missing content_type "animation"

- README.md
- telebot/__init__.py
Recently, when I tried to add some filters, you rejected and said, the only is_private can be useful. So I created is_private filter
> is_private filter

- telebot/__init__.py
- telebot/util.py
Added new feature - from now you can create your own custom filters.
Here are some examples of how to use it.
You can make any check you want. Class should have .check() method, and should have message attribute.
Message update passes to your custom filter, and it runs your filter's check method.
> Custom filters

- README.md
- telebot/version.py
New feature: custom filters!
Pre 4.1.0 release.
> 4.0.1 beta release

- examples/custom_filters/is_filter_example.py
- telebot/custom_filters.py
Added example on 2 filters. And, edited description for a built-in filter.
> Added example and editd description.

- examples/anonymous_bot.py
Hello, i added new example - anonymous chat-bot
With this bot, you will be able to find random users and communicate with them
> Added new example: anonymous chat-bot

- telebot/__init__.py
Added property `user` to TeleBot class. The idea is to have easy access to the user object representing the bot without doing an API call every time.
> added property `user` to TeleBot class

- examples/custom_states.py
- telebot/__init__.py
- telebot/custom_filters.py
- telebot/handler_backends.py
Fix on state handlers:
- no more need to use state handlers. State filter can be used on any handler
- Added new filter
> Update of state handlers

- telebot/apihelper.py
Added RETRY_ENGINE var to api_helper.
Added RETRY_ENGINE = 2 based on native "requests" retry mechanism.
> RETRY_ENGINE

- README.md
Added Google Sheet bot to list of bot examples in README.md
> added Google Sheet bot to list of bot examples.

- README.md
Hi, I used your python API during my master's degree final project for a trivia game based bot. I hope you will find it interesting and a good example for your project.
Regards,
Carlos.
> Add GrandQuiz Bot by Carlosma7

- README.md
- examples/asynchronous_telebot/download_file_example.py
- examples/asynchronous_telebot/exception_handler.py
- examples/asynchronous_telebot/middleware/flooding_middleware.py
- examples/asynchronous_telebot/middleware/i18n.py
- examples/asynchronous_telebot/send_file_example.py
Fixes with an asynchronous version of telebot:
- Created examples on sending and downloading files, middlewares, and exception handler
- Improvement of making requests
- Exception Handler Added
- Readme updated
> Exception handler, Boolean Fix and more

- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_handler_backends.py
- telebot/asyncio_helper.py
- telebot/handler_backends.py
- telebot/util.py
- telebot/version.py
- tests/test_telebot.py
Bugfix in send_data
Protected methods renamed
Some hints added
> Bugfix in send_data

- examples/asynchronous_telebot/timer_bot_async.py
- examples/timer_bot.py
Add example for my [issue 1415](https://github.com/eternnoir/pyTelegramBotAPI/issues/1415)
> Add timer_bot sync and async example

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- tests/test_types.py
Bot API 5.7
Added support for Video Stickers.
Added the field is_video to the classes Sticker and StickerSet.
Added the parameter webm_sticker to the methods createNewStickerSet and addStickerToSet.
> Bot API 5.7

- .github/PULL_REQUEST_TEMPLATE.md
- doc_req.txt
- telebot/__init__.py
- telebot/callback_data.py
- telebot/types.py
- telebot/util.py
Fixed 'latest' version for documentation. The latest version will contain GitHub version
Created offline HTML documents using the command make html. Also, I tested it on fork-documentation.
OS: Big Sur
> Regular documentation update.

- telebot/asyncio_helper.py
> Issue #1491: missing await inserted

- telebot/__init__.py
- telebot/asyncio_filters.py
- telebot/asyncio_helper.py
- telebot/custom_filters.py
Changed behavior of filters, fixed #1488, added warning.
OS: Big Sur
> Road to release(1st part)

- docs/source/conf.py
- examples/asynchronous_telebot/chat_member_example.py
- examples/chat_member_example.py
- examples/payments_example.py
- setup.py
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/util.py
- telebot/version.py
Bot API 6.0. Deprecation fixes
- [v] I added/edited example on new feature/change (if exists)
- [v] My changes won't break backend compatibility
- [v] I made changes for async and sync
> Bot API 6.0. Deprecation fixes

- telebot/custom_filters.py
i18n middleware - custom_filters.py revert
> i18n middleware - file revert

- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
Bugfix in answer_web_app_query
> Bugfix in answer_web_app_query

- telebot/types.py
Mistake in ChatAdministratorRights fix
> Mistake in ChatAdministratorRights

- docs/source/formatting.rst
- docs/source/index.rst
- examples/asynchronous_telebot/formatting_example.py
- examples/formatting_example.py
- telebot/__init__.py
- telebot/formatting.py
I created a new file which contains all functions that are necessary for markdown and html.
With those functions, you can achieve formatting easier and faster.
Every function was tested by sending message.
OS: MacOs BigSur
> Markdown & Html functions added(Beta version, still in progress)

- telebot/__init__.py
Polling exception logging arranged with infinity_polling mode
Added custom logging_level for polling function. Now internal polling excetions are managed in the same way as infininty_polling ones.
> Polling exception logging updated

- telebot/asyncio_filters.py
- telebot/custom_filters.py
> Key for custom filters

- README.md
- telebot/asyncio_helper.py
> Fixed proxy for asynctelebot

- docs/source/async_version/index.rst
- docs/source/calldata.rst
- docs/source/formatting.rst
- docs/source/index.rst
- docs/source/install.rst
- docs/source/quick_start.rst
- docs/source/sync_version/index.rst
- docs/source/util.rst
> Seo improvements for documentation.

- telebot/asyncio_storage/memory_storage.py
- telebot/asyncio_storage/pickle_storage.py
- telebot/asyncio_storage/redis_storage.py
- telebot/storage/memory_storage.py
- telebot/storage/pickle_storage.py
- telebot/storage/redis_storage.py
> Allow only state objects

- telebot/storage/redis_storage.py
> Random unused import deleted

- docs/source/conf.py
- telebot/version.py
> Bump version to 4.5.1

- README.md
I request that my bot is added to the "bots using this api" section.
> updated the "bots using this api" section in README

- telebot/types.py
Make some class fields optional according to Bot API.
> class File parse fix

- examples/asynchronous_telebot/multibot/README.MD
- examples/asynchronous_telebot/multibot/config.py
- examples/asynchronous_telebot/multibot/handlers.py
- examples/asynchronous_telebot/multibot/main.py
- examples/asynchronous_telebot/multibot/nginx_conf.conf
- examples/multibot/README.MD
- examples/multibot/config.py
- examples/multibot/handlers.py
- examples/multibot/main.py
- examples/multibot/nginx_conf.conf
Examples of multibot (sync and async)
> added examples of multibot

- .github/PULL_REQUEST_TEMPLATE.md
- telebot/asyncio_storage/redis_storage.py
- telebot/storage/redis_storage.py
- telebot/types.py
Poll type parameter parse fix
Plus some typo
> Poll type parameter parse fix

- examples/asynchronous_telebot/formatting_example.py
- examples/formatting_example.py
- telebot/formatting.py
Added ability to hide a link in text
OS:
> Added ability to hide a link in text

- requirements.txt
- telebot/asyncio_helper.py
Improvements were done for asyncio_helper file.
OS:
> Aiohttp client session management improvements.

- README.md
> More description for class-based middlewares in readme.

- telebot/util.py
`validate_WebApp_data()` - Use to validate the data received by the WebApp from Telegram.
`parse_WebApp_data()` - Use to parse the data sent to the WebApp from the bot's backend.
> Added `WebApp` functions

- README.md
source code available here 
https://github.com/tusharhero/bincode-telegram-bot
OS:
> Added my bot made using pyTelegramBotAPI

- README.md
add hydrolib_bot to Bots using this library in README.md
OS:
> add hydrolib_bot to Bots using this library

- telebot/asyncio_storage/pickle_storage.py
- telebot/storage/pickle_storage.py
> Fix bug with unsaving data

- README.md
- docs/source/conf.py
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/version.py
- tests/test_types.py
Join Requests & Payments
Premium fields
Attachment menu
Webhooks
See https://core.telegram.org/bots/api#june-20-2022 for more
> Bot API 6.1 update

- telebot/asyncio_filters.py
- telebot/asyncio_helper.py
- telebot/custom_filters.py
> Fix group and supergroup issues with states

- README.md
> Add my bot to README.md

- telebot/async_telebot.py
#1594 & fixes regarding handler execution in async
> #1594 & fixes regarding handler execution in async

- telebot/async_telebot.py
- telebot/types.py
- telebot/util.py
ChatMember is now typed.
https://core.telegram.org/bots/api#chatmember
Added source data (json_string) to CallbackQuery (https://github.com/eternnoir/pyTelegramBotAPI/pull/1586)
> ChatMember is now typed

- telebot/__init__.py
> Fix exception with typed_middleware_handlers

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/asyncio_handler_backends.py
- telebot/handler_backends.py
- Added update_sensitive field for middlewares. By default, it is false.
If it is set to True, then depending on the [update_type](https://pytba.readthedocs.io/en/latest/types.html#telebot.types.Update), a function will be executed. Here is an example:
I created a basic example for sync and async, then I debugged the functions.
Python version: 3.10.2
OS: Windows
> update_sensitive field for middlewares

- telebot/__init__.py
> Fixed description

- telebot/asyncio_helper.py
> Fixes #1637, #1636

- telebot/__init__.py
- telebot/handler_backends.py
Updated all docstrings / typehints in __init__.py(visual)
I'll work on other files as soon as this PR gets merged. I'll do another PR for those files.
> Updated all docstrings / typehints in __init__.py(visual)

- examples/asynchronous_telebot/webhooks/async_webhook_aiohttp_echo_bot.py
An async echo bot using aiohttp and webhoook
Python version: 3.9
OS: Debian 11.4
> Example of async bot using webhook and aiohttp

- telebot/apihelper.py
- telebot/asyncio_helper.py
- telebot/types.py
InputFile is an easier way to send files. It is present in API, so I thought it would be useful to have it.
Tested for all methods(send_xyz)
Python version: 3.10.2
OS: Windows 10
> Added InputFile

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- tests/test_types.py
Bot API 6.2
Custom Emoji Support
**Web App Improvements**
-- Has nothing to do with library, so skipped -- 
**Other Changes**
> Bot API 6.2

- telebot/types.py
Fixed issue #1650
I tried to send different posts with bunch of entities. 
Python version: 3.10.2
OS: Windows 10
> Fixed #1650

- telebot/__init__.py
> Fixed bug with searching a new handler after the execution of handler

- telebot/__init__.py
- telebot/async_telebot.py
**Code simplify and sync/async unification**
> Code simplify and sync/async unificatiion

- examples/asynchronous_telebot/webhooks/webhook_starlette_echo_bot.py
Add a Starlette ASGI example using async telebot.
I ran the example.
OS: Linux
> Starlette ASGI example

- telebot/asyncio_helper.py
getUpdates parameter may contain 2 parameters: request_timeout & timeout. other methods may contain timeout parameter that should be applied to ClientTimeout.
> Fixed difference between request_timeout and timeout.

- telebot/__init__.py
- telebot/async_telebot.py
Added:
- disable_web_page_preview
- disable_notification
- protect_content
- allow_sending_without_reply
OS: Big Sur
> ⚙️ Added some frequent parameters to classes(see full list)

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/ext/sync/webhooks.py
- telebot/storage/base_storage.py
- telebot/storage/memory_storage.py
- telebot/storage/pickle_storage.py
- telebot/storage/redis_storage.py
Call for handlers now union in a single function for future extension.
Plus minor fixes in storages.
> Handlers and Middlewares processing union

- examples/asynchronous_telebot/detect_changes.py
- examples/detect_changes.py
- setup.py
- telebot/__init__.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/ext/reloader.py
Improvements in logging, file restarts, cached user property for async
Tested each change by myself, but file restarts on changes needs to be tested on other platforms as well.
OS: Big Sur
- Example is not created yet
> Logging improvements(still not 100%), file restarts on file changes(needs tests), and more

- telebot/apihelper.py
Check CUSTOM_REQUEST_SENDER before RETRY_xxx.
> Check CUSTOM_REQUEST_SENDER before RETRY_xxx.

- examples/asynchronous_telebot/continue_handling.py
- examples/continue_handling.py
- telebot/__init__.py
- telebot/async_telebot.py
- telebot/asyncio_handler_backends.py
- telebot/handler_backends.py
basic implement for https://github.com/eternnoir/pyTelegramBotAPI/pull/1704
> Support ContinueHandling

- telebot/__init__.py
- telebot/async_telebot.py
Made params local, so that it is unique for each handler. This bug is related to middlewares+continuehandling
> Continuehandling fix

- .github/workflows/setup_python.yml
- .travis.yml
- README.md
- docs/source/conf.py
- telebot/version.py
Bump version to 4.8.0 and update Python versions
> Bump version to 4.8.0 and update Python versions

- docs/source/locales/ru/LC_MESSAGES/formatting.po
> Translated into russian file: formatting.po

- docs/source/locales/ru/LC_MESSAGES/util.po
> Translated to russian file: util.po

- telebot/types.py
Fix caption_entities miss in InputMediaXXX
> Fix caption_entities miss in InputMediaXXX

- telebot/__init__.py
Fixed register_next_step_handler_by_chat_id chat_id description
> Fixed register_next_step_handler_by_chat_id chat_id description

- telebot/asyncio_helper.py
> Fix bug related to get_user_profile_photos

- docs/source/locales/ru/LC_MESSAGES/sync_version.po
Translated part of sync_version.po file, till edit_message_media()
OS:
> Partly translated files: sync_version.po

- docs/source/locales/ru/LC_MESSAGES/async_version.po
- docs/source/locales/ru/LC_MESSAGES/sync_version.po
Minor fixes in sync_version.po, found while copying
OS:
> Copied translations from sync_version.po to async_version.po

- docs/source/locales/ru/LC_MESSAGES/async_version.po
- docs/source/locales/ru/LC_MESSAGES/sync_version.po
- telebot/__init__.py
- telebot/async_telebot.py
Minor fixes in previous translations
Fixed typehints for reply_markup in stop_poll method
OS:
> Finished transltaions into russian of files: sync_version.po, async_version.po

- docs/source/locales/ru/LC_MESSAGES/calldata.po
- docs/source/locales/ru/LC_MESSAGES/index.po
> Translated into russian files: index.po, calldata.po

- telebot/service_utils.py
- Added ImportError to block except to be more specific on errors related to pillow lib
- Removed io lib from try/except block since it is built-in lib
OS:
> Little code style improvement in service_utils

- telebot/util.py
This method is used to get file id of different types of media
OS:
> Create method get_media_file_id() in util.py

- telebot/types.py
> Fix type of attribute id of InlineQuery from int to str

- telebot/asyncio_helper.py
> Async allowed_updates fix

- examples/poll_example.py
An example file on how to create polls and handle poll answers
Python version:  3.9.7
OS: Ubuntu 20.04.1
> Added poll_example.py in the examples

- telebot/apihelper.py
- telebot/asyncio_helper.py
Fix bug with use_independent_chat_permissions in restrict_chat_member.
> restrict_chat_member fix

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/util.py
New content types added + typo fix
> New content types added + typo fix

- telebot/util.py
- tests/test_telebot.py
Add `extract_entity` in  `util.py` to extract contents of entities from messages.
Send a message and compare the extracted contents of returned entities to the correct ones
Python version:3.10
OS: Windows
> Add a function to extract contents of entities from messages

- README.md
I added my new telegram bot (Spot Seek Bot) to list of the bots that use this library.
> add SpotSeekBot 

- telebot/asyncio_handler_backends.py
- telebot/handler_backends.py
> Add state_list to StatesGroup

- .readthedocs.yaml
https://docs.readthedocs.io/en/stable/config-file/v2.html
> Fixed deprecation warning for readthedocs.org

- docs/source/locales/en/LC_MESSAGES/async_version.po
- docs/source/locales/en/LC_MESSAGES/sync_version.po
- docs/source/locales/en/LC_MESSAGES/types.po
- docs/source/locales/en/LC_MESSAGES/util.po
- docs/source/locales/ru/LC_MESSAGES/async_version.po
- docs/source/locales/ru/LC_MESSAGES/sync_version.po
- docs/source/locales/ru/LC_MESSAGES/types.po
- docs/source/locales/ru/LC_MESSAGES/util.po
> Updated all russian docstrings, currently without translation.

- telebot/async_telebot.py
> Fix issue with post_process in async not receiving the error

- telebot/types.py
@Badiboy i'm not really sure about this: Basically i am creating random string for file name in InputFile for memory-uploaded files. Do you think it is fine?
> Fixes #1944: uploading file from memory

- .github/workflows/setup_python.yml
- .readthedocs.yml
- .travis.yml
- README.md
- docs/source/conf.py
- telebot/version.py
> Bump version to 4.13.0

- telebot/__init__.py
Fix protect_content hint in send_message
> Fix protect_content hint

- README.md
> adding QR-Code Generator bot to the list

- telebot/apihelper.py
send_document with InputFile and visible_file_name fails to be sent.
> Sending InputFile fix

- README.md
> add instagram downloader to bots list

- docs/source/conf.py
- telebot/version.py
> Bump version

- telebot/__init__.py
- telebot/types.py
- telebot/util.py
> Post-huge update fix #2: deprecations

- docs/source/locales/en/LC_MESSAGES/async_version.po
- docs/source/locales/en/LC_MESSAGES/sync_version.po
- docs/source/locales/en/LC_MESSAGES/types.po
- docs/source/locales/ru/LC_MESSAGES/async_version.po
- docs/source/locales/ru/LC_MESSAGES/sync_version.po
- docs/source/locales/ru/LC_MESSAGES/types.po
> Doc update

- docs/source/locales/ru/LC_MESSAGES/async_version.po
- docs/source/locales/ru/LC_MESSAGES/sync_version.po
Translated description of the get_user_chat_boosts method for sync and async versions
> Doc translate

- docs/source/conf.py
- telebot/version.py
> Bump version to 4.15.0

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/types.py
Fix disable_web_page_preview to is_disabled in LinkPreviewOptions
> Fix disable_web_page_preview in LinkPreviewOptions

- telebot/apihelper.py
Bugfix: fix link_preview_options passing for Telebot
> Bugfix: fix link_preview_options passing for Telebot

- docs/source/conf.py
- telebot/version.py
Bump version to 4.15.1 (bugfix release)
> Bump version to 4.15.1 (bugfix)

- docs/source/conf.py
- telebot/version.py
> Bump version to 4.15.2

- docs/source/conf.py
- telebot/version.py
> Bump version to 4.15.3

- docs/source/conf.py
- telebot/types.py
- telebot/version.py
Bugfix in ChatBoostSource parse
Version bump to 4.15.4
> Bugfix in ChatBoostSource parse

- telebot/types.py
> One more fix for BoostSource

- docs/source/conf.py
- pyproject.toml
- telebot/version.py
> Bump version to 4.15.5

- .travis.yml
- README.md
- pyproject.toml
> Fix Python versions 3.8-3.12

- docs/source/conf.py
- pyproject.toml
- telebot/types.py
- telebot/version.py
Fix ChatBoostSourceGiveaway and bump version
> Fix ChatBoostSourceGiveaway and bump version

- telebot/types.py
Fix GiveawayCreated not implemented
> Fix GiveawayCreated not implemented

- README.md
- docs/source/conf.py
- pyproject.toml
- telebot/version.py
Readme fix + bump version to 4.16.1
> Readme fix + bump version to 4.16.1

- README.md
Added my bot source link to the README.md.
> Added my bot source link to the repository.

- examples/asynchronous_telebot/message_reaction_example.py
- examples/message_reaction_example.py
Hello, I have created simple example of telegram bot (sync and async), it send message reactions (emoji) in response to received messages and receive changes in message reactions.
These are examples for them, tests are not needed.
Python version: All
OS: All
> Example bot using message reactions (emoji)

- telebot/async_telebot.py
Fixed one word with grammar error
> Fix grammar error

- docs/source/conf.py
updating the copyright date from 2023 to 2024
OS:
> update: copyright date

- docs/source/conf.py
> automatic updates of copyright year in lib

- telebot/__init__.py
- telebot/async_telebot.py
- Pass default parse mode to Media items:
https://github.com/eternnoir/pyTelegramBotAPI/issues/2232
- Hide token in exception messages:
https://github.com/eternnoir/pyTelegramBotAPI/issues/2227
> Some issue fixes

- docs/source/conf.py
> Removed the tautology in the documentation title

- examples/asynchronous_telebot/echo_bot.py
> Update async echo_bot example

- README.md
Nothing much but an update to **bots using this library**.
- [Pytgpt-bot](https://github.com/Simatwa/pytgpt-bot) provides seamless interaction with multiple LLM providers for natural language chatting, generating images from prompt and also speech synthesis.
OS:
- [x ] My changes won't break backward compatibility
> Add pytgpt-bot to bots using this library.

- telebot/asyncio_filters.py
Revert changes from https://github.com/eternnoir/pyTelegramBotAPI/pull/2251
> Revert add type hints to SimpleCustomFilter

- telebot/types.py
Fix MessageEntity.user if None
> Fix MessageEntity.user if None

- telebot/apihelper.py
fixed copy_message in apihelper.py
> fixed copy_message in apihelper.py

- docs/source/conf.py
- pyproject.toml
- telebot/__init__.py
- telebot/apihelper.py
- telebot/version.py
Bump version for bugfix release
> Bump version for bugfix release

- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
Add "timeout" parameter to edit_xxx functions to align them with send_xxx functions.
> Add "timeout" parameter to edit_xxx functions

- telebot/custom_filters.py
- telebot/types.py
Suppress warnings and fix forward_origin
> Suppress warnings and fix forward_origin

- telebot/types.py
Fix html_text for None. Return None instead if exception.
> Fix html_text for None

- telebot/types.py
https://github.com/eternnoir/pyTelegramBotAPI/pull/2356
> Fix html_caption for None. Return None instead if exception.

- docs/source/conf.py
- pyproject.toml
- telebot/version.py
Bump version for intermediate release: New states and fix middlewares
> Bump version for intermediate release

- telebot/asyncio_filters.py
- telebot/custom_filters.py
> Fix states for webhooks

- telebot/types.py
Fix some type hints and warnings
1. Several typehint fixes
2. 1 return bug fix
3. BuiltIn hints suppressed to make hint check easier
> Fix some type hints and warnings

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Botapi 7.11

- .github/workflows/setup_python.yml
- .travis.yml
- README.md
- docs/source/conf.py
- pyproject.toml
- telebot/version.py
Version bump and python upgrade
> Version bump and python upgrade

- README.md
These days the bot no longer generates HTML, only images.
> Update colorcodebot description

- examples/stars_payment.py
This is a example how to make a payment using telegram stars.
Python version tested: 3.12.8
> Added new example: stars payment bot

- telebot/asyncio_filters.py
Closed https://github.com/eternnoir/pyTelegramBotAPI/issues/2458
How did you test your change? -
Python version: -
OS: -
> Issues 2458: missing `in`

- README.md
Add BetterForward to bots list
> Add BetterForward to bots list

- docs/source/conf.py
- pyproject.toml
- telebot/version.py
> Bump version to 4.27

- telebot/util.py
1. content_type_media, content_type_service, update_types  ordered according to presence in code to make add missing ones easier.
2. Added some missed content types.
> content_type_xxx aligned
