- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
I made two small commits, one concerning the ReplyKeyboardMarkup class and another to implement the offset parameter in the getUpdates API call (see https://core.telegram.org/bots/api#getupdates)
The ReplyKeyboardMarkup additions made my life a whole lot easier, I just thought I'd share.
The other commit was necessary to fix an internal bug my bot was experiencing, where I would only get up-to-date Updates when I passed the offset parameter along with the getUpdates call. This commit might improve the efficiency of the TeleBot#get_update function as well.
> Extending ReplyKeyboardMarkup and implementing the offset getUpdates parameter

- .travis.yml
- README.md
- telebot/__init__.py
- telebot/apihelper.py
small fixes to make telebot compatible with python3. I would prefer using logging, but there's not much use in the module now so maybe later.
also two very small two space PEP8 fixes.
> make telebot compatible with python3

- README.md
- examples/echo_bot.py
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
Added TeleBot#reply_to(message, text)
Extended message_handler decorator to accept argument 'commands' (E.g. commands=['start', 'help'] will qualify this message_handler for /start and /help
TeleBot now makes use of the timeout argument of getUpdates (so-called long polling), which is more effective compared to using time.sleep.
Updated README.md.
AsyncTeleBot is a subclass of TeleBot and therefore inherits all of TeleBot's properties. It simply modifies some functions to be asynchronous.
AsyncTeleBot example:
```python
bot = telebot.AsyncTeleBot(TOKEN)
task1 = bot.get_me() # Fires an async API call.
assert isinstance(task1, telebot.AsyncTask)
task2 = bot.send_message(chat_id, "Hi how are you!") # Also async
assert isinstance(task2, telebot.AsyncTask)
me = task1.wait() # Gets the result …
```
> Added AsyncTeleBot

- README.md
- telebot/__init__.py
- telebot/apihelper.py
Added a warning to send_message to not exceed 5000 characters per message.
Changed send_message to use HTTP POST instead of GET, to stretch the maximum character limit a little more.
> Added split_string to apihelper.py

- README.md
- README.rst
- examples/webhook_examples/README.md
- examples/webhook_examples/webhook_cherrypy_echo_bot.py
- examples/webhook_examples/webhook_cpython_echo_bot.py
- examples/webhook_examples/webhook_flask_echo_bot.py
This commit have 3 parts:
- Adds a webhook_examples directory inside examples with 3 examples and a readme.
- Update main README.md with the info regarding webhooks (and my emacs deleted a couple of trailing whitespace).
- Update README.rst (converted README.md)
> Add webhook examples

- telebot/apihelper.py
Hi,
The default GET used by answer_inline_query() produces `414 Request-URI Too Large` response.
This should fix the issue.
> answer_inline_query() made POST

- telebot/types.py
Changed `titlee` to `title`
I have a type (how ironic!) in commit. `Audio` needs to be fixed, not `Article`
> Fixed typo in InlineQueryResultAudio

- telebot/types.py
"switch_inline_quer" -> "switch_inline_query"
> Fixed typo in types.py

- telebot/util.py
`telebot/util.py` was missing the import of the `re` module required for `extract_arguments()` function.
> Added missing import for extract_arguments()

- examples/webhook_examples/webhook_flask_echo_bot.py
I just find that in the flask webhook example, request.get_data() return a value whose type is 'byte' instead of 'string'. And it will cause an error shown below
```
ValueError: json_type should be a json dict or string.
```
This commit is a patch that decode the byte value into string using decode('utf-8').
> Fix the bug that the return of request.get_data() is not string.

- examples/webhook_examples/webhook_cherrypy_echo_bot.py
This way all types of queries (Message, Inline query, Callback query) are supported.
> Changed "Process_new_message" to "Process_new_update"

- telebot/types.py
Add support of python2 unicode stings for types.check_json.
> unicode strings for check_json

- telebot/types.py
Occasionally, `Game` object is parsed as `Photo` (99% sure it's just typo).
> Fixed API object type mismatch

- telebot/types.py
obj['data'] raises KeyError when `data` is None, while obj.get('data') returns None
> Fixed KeyError when data field is None in CallbackQuery

- telebot/apihelper.py
Requests's sessions [provide](http://docs.python-requests.org/en/master/user/advanced/#keep-alive) connection reuse, read more about [HTTP Keep-Alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection) in Wikipedia.
> Use session to ensure persistent connection to api.telegram.org

- README.md
Line 184: from `return message.document.mime_type == 'text/plan'` to `return message.document.mime_type == 'text/plain'`
> Fixed typo: from plan to plain

- telebot/__init__.py
- telebot/apihelper.py
Added option to delete messages.
Some bots do not support `deleteMessage` method now, waiting for an official api update
release.
So, here is a small [script](https://gist.github.com/Kylmakalle/1132315523fee96c386b3330cdcdde13) to check possibility of your bot to delete messages **NOW**, while this method in non-release stage
**UPD: 08.05** Now 6/10 my bots can delete messages, telegram updates our bots gradually
**UPD: 12.05** 8/10 can delete messages, old bots updated.
**UPD: 14.05** 9/10 can delete messages, new bot updated
> Added option to delete messages.

- telebot/apihelper.py
If a file is sent to the bot and "download_file(token, file_path)" is called, and the file happens to have unicode characters in its name e.g "ردیاب شماره و دسترسی.apk" the following error is thrown.
The reason is because FILE_URL is defined as simple ascii string without u"" notation.
```
six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 54, in run
task(*args, **kwargs)
File "Telescam_scanner_bot.py", line 246, in on_receive_file
downloaded_file = bot.download_file(file_info.file_path)
File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 313, in download_file
return apihelper.download_file(self.token, file_path)
File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line …
```
> Fixed unicode formatstring issue

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
Send and receive round video messages.
Support for `send_video_note` method and `video_note` content type.
[Take a look](https://github.com/eternnoir/pyTelegramBotAPI/pull/338/files#diff-9b5a06a5a5b33ef7c3d1268ac38b778aR338) at `length` parameter, I have made some tests and found out that
only numbers in range `(0, 640)` are working, else you will got an error: `{"ok":false,"error_code":400,"description":"Bad Request: wrong video note length"}`, but there are no any restrictions about video note [length](https://core.telegram.org/bots/api#sendvideonote), by the way, i do not see any changes in `video_note` after `length` parameter use. 
Also changing a duration of `video_note` does not affect it in a right way, just check [@videonote](https://t.me/videonote) and [this …
> Video Note support.

- examples/payments_example.py
Small payment bot example.
More about Payments: https://core.telegram.org/bots/payments
Analogue of official [Shop Bot](https://t.me/ShopBot) 
**Note:** Some [info is missed](https://cloud.githubusercontent.com/assets/24507532/26463790/3003e48e-418e-11e7-85aa-6b8a9916097a.png) in `shipping_address`, so `is_flexible` is `False` in this example (_we need a working one, right?_)
Maybe it is about test Stripe token, not live.
> Added payments example

- telebot/__init__.py
Should be called `apihelper.answer_shipping_query` instead of `apihelper.answer_shippingQuery`
Fixes `AttributeError: module 'telebot.apihelper' has no attribute 'answer_shippingQuery'`
> Fixed wrong method call

- telebot/apihelper.py
Without this code Telegram Bot API will never get a correct json with set up `allowed_updates` field.
Before this code it's easy to check that passing allowed_updates does not work:
1. send `setWebhook` command with passed `allowed_updates = ['message']` (for example)
2. send `getWebhookInfo` command and you will get `allowed_updates: None` in response.
3. That's why bot continues to get updates non-message type.
> json.dumps(allowed_updates) before sending request

- telebot/apihelper.py
- telebot/util.py
It's not safe to use global requests.Session instance in threaded application, so I made sessions thread-local. For more info see: https://github.com/requests/requests/issues/2766
> Per-thread requests sessions

- README.md
- README.rst
The interface of `TeleBot.polling()` in module telebot has changed. The old `block` parameter is removed and a `timeout` is added, but the readme documents don't reflect these changes.
> change the documentation of TeleBot.polling in readme

- telebot/types.py
`author_signature` field was checked, but never added to `Message` object.
> Added missing author_signature field to Message object

- telebot/__init__.py
Hello. There is an error in register_next_step_handler: when new message comes, callback function is called. Its okey. But it processes like regular message, too. 
Look: I have handler for text and then check if message.text == "/start" and etc. An if it doesn't match any command it send unknown command message. So when user sends message after register_next_step_handler, it send message from callback function and from handler! So I fixed this bug.
Issues:
https://github.com/eternnoir/pyTelegramBotAPI/issues/405
https://github.com/eternnoir/pyTelegramBotAPI/issues/315
> #405 - Message has callback function but it exec command handlers too.

- telebot/apihelper.py
- telebot/types.py
- telebot/util.py
Added support for local files in the `send_media_group` method
For example:
```python
import telebot
from telebot.types import InputMediaPhoto, InputMediaVideo
bot = telebot.TeleBot(token)
@bot.message_handler(commands=['get'])
def get_media(message):
with open('path/to/file1.jpg', 'rb') as f1, open('/path/to/file2.jpg', 'rb') as f2, \
open('/path/to/video.mp4', 'rb') as video:
files = bot.send_media_group(message.from_user.id,
[InputMediaPhoto(f1),
InputMediaPhoto(f2),
InputMediaPhoto(<url>),
InputMediaPhoto(<file_id>),
InputMediaVideo(video)])
```
> Added support for local files in the sendMediaGroup method

- telebot/__init__.py
- telebot/apihelper.py
- telebot/types.py
- tests/test_telebot.py
- Supported text formatting in media captions. Specify the desired parse_mode (Markdown or HTML) when you provide a caption. Example:
```python
bot.send_photo(chat_id, photo, caption='<b>bold text</b>, parse_mode='HTML')
```
- In supergroups, if the bot receives a message that is a reply, it will also receive the message to which that message is replying – even if the original message is inaccessible due to the bot's privacy settings. (In other words, replying to any message in a supergroup with a message that mentions the bot or features a command for it acts as forwarding the original message to the bot).
- Added the new field _connected_website_ to Message. The bot will receive a message with this field in a private chat when a user logs in on the bot's connected website using the …
> Bot Api 3.6

- telebot/apihelper.py
Hi there,
This PR fix UnicodeEncodeError when sending a non-ASCII file in python 2.7.
Please refer to my previous issue #403
Thanks!
> fix issue #403: UnicodeEncodeError when sending a non-ASCII file in Python 2

- telebot/__init__.py
After calling
`clear_step_handler(...)`
the code:
`self.next_step_handlers[chat_id] = []`
left the key in next_step_handlers. When a next message arrives, the old handler executes nothing (no handlers), but still remove message from message queue:
`new_messages.pop(i)`
Updated to pop message only when there are real handlers in the list.
> _notify_next_handlers drops messages if empty handler list

- telebot/types.py
This check prevents errors from the API, which expects the optional parameter `parse_mode` to be a string rather than `null`, so that the parameter is only added to the JSON payload if it is present.
Should fix #571
> Add check for parse_mode in BaseInlineQueryResultCached

- telebot/apihelper.py
Because of issue #613 
These methods must return 'Message' entity, but return True
https://core.telegram.org/bots/api#editmessagetext
> Add 'method' parameter to methods that edit message

- telebot/__init__.py
Sleep the getUpdates timeout time instead of 5 seconds to avoid looping into conflict exception
> infinity_polling fix

- telebot/apihelper.py
Fixed AttributeError that was caused by referencing `file_path` in object-attribute style on dict:
`get_file(token, file_id).file_path`
telebot/apihelper.py:101
```
def get_file_url(token, file_id):
return FILE_URL.format(token, get_file(token, file_id)['file_path'])
```
**Why to reference as a dict item but not to de_json right here**
`get_file` function of apihelper.py returns a dict that is not converted to an object yet (as all functions in apihelper.py do).
De-json'ing of `apihhelper.get_file()` takes place in `TeleBot.get_file()`.
telebot/__init__.py:483
```
def get_file(self, file_id):
return types.File.de_json(apihelper.get_file(self.token, file_id))
```
> Fixed #578

- examples/inline_example.py
Use ==/!= to compare str, bytes, and int literals because identity is not the same thing as equality in Python. These instances will raise SyntaxWarnings on Python >= 3.8 so it is best to fix them now. https://docs.python.org/3.8/whatsnew/3.8.html#porting-to-python-3-8
> Use ==/!= to compare str, bytes, and int literals

- telebot/types.py
Setting list of ShippingOptions like in payments_example.py
shipping_options = [
ShippingOption(id='instant', title='WorldWide Teleporter').add_price(LabeledPrice('Teleporter', 1000)),
ShippingOption(id='pickup', title='Local pickup').add_price(LabeledPrice('Pickup', 300))]
gives us [None,None],so It's better add_price to return self
> Update shipping option

- .travis.yml
Travis: removed 2.6 and 3.3 (not supported). Added 3.7. Also added 3.8 (for experiment)
> Update version list in travis.yml

- telebot/__init__.py
- telebot/apihelper.py
Added the method sendAnimation, which can be used instead of sendDocument to send animations, specifying their duration.
https://github.com/eternnoir/pyTelegramBotAPI/issues/542
> sendAnimation

- telebot/__init__.py
- telebot/types.py
Pretty straight-forward edits, implemented similarly to other handlers. Updated `types.Poll` so it stores all fields passed by Telegram.
Can be used similar to other handlers:
```
@bot.poll_handler(func=lambda call: True)
def handle_vote(poll):
print poll
```
Didn't update README and didn't write any tests/examples.
> Add @bot.poll_handler to be notified of new poll states

- telebot/__init__.py
- telebot/apihelper.py
With apihelper.CUSTOM_SERIALIZER you can replace pickle with other "dumper" like dill.
> Possibility to use alternative serializer

- telebot/__init__.py
This pull request fixes not needed all the time invocations on typed middleware handlers even if `update` did not have that `update_type` message.
It closes #800
> Fix not needed invocations on typed middleware handlers

- tests/test_handler_backends.py
To enable REDIS set
test_handler_backeds.REDIS_TEST = True
before running tests.
> Disable REDIS tests to save Travis

- README.md
Added my bot into the list of "Bots using this API" in the README file. The bot will remove the "joined group" or "removed from group" notification. The repository is included as well so others can use the code if they need to add this functionality in their bot.
> Added JoinGroup Silencer Bot into the "Bots using this API" in README

- telebot/types.py
Before these commits bots could not parse `strikethrough` and `underline` text entities. However now it can.
> Added two more entities to parse to html

- telebot/apihelper.py
Replacing 1 exception class with 3 more specific classes: 
- HTTP Exception (server returned http code != 200)
- Invalid JSON Exception (server returned invalid json)
- Telegram Expection (telegram returned ok != true)
All 3 classes extend BaseApiException so we can easily handle all API exceptions at the same time
> Exception classes redesign

- telebot/__init__.py
- telebot/types.py
- telebot/util.py
- add() method now has a row_width parameter, self.row_width is used if row_width is not specified
- add() and row() methods now support auto row splitting
- add() method now also returns self to allow function chaining
- add() method now throw a ValueError exception if row_width >8 (for inline keyboard) or >12 (for reply keyboard), before this telegram just ignored buttons that didn't fit
Also, type-checking moved to utils to keep code consistent
> Minor keyboard code redisign

- telebot/apihelper.py
Changes:
- Now API request can return only one exception per time
- ApiTelegramException now has error_code field, which contains telegram api error code
- API methods now return None if there was error while execution
- Bug fixed
> Exceptions classes redesign followup

- telebot/util.py
When I've tried to send_photo as shown in detailed_example, I got an error: "AttributeError: module 'PIL' has no attribute 'Image'". 
This error was described well here: https://stackoverflow.com/a/11911536/9092263. So in accordance to prescriptions, I've made changes and It works fine for me.
Steps to reproduce:
1. initiate bot via TeleBot constructor
2. call function `bot.send_photo(call.message.chat.id, open("some_image.jpg", "rb"))`
P.S.
Error Environment: 
- python==3.8.5
- pyTelegramBotAPI==3.7.3
- PIL==7.2.0
> Fix an error with the is_pil_image function

- telebot/types.py
"When you send gif telegram gives you animation and document at same time in update and when you parse that first if is animation and second is document because of this the content_type set document not animation"
> Animation content_type

- telebot/apihelper.py
set_webhook does not reset allowed_updates for empty list (to default)
> set_webhook bugfinx

- telebot/apihelper.py
В telegram bot api метод restrictChatMember принимает JSON строку с описанием всех разрешений. Telebot в свою очередь пихает все эти разрешения как отдельные параметры когда делает запрос к API телеги, из-за чего разрешения раздать не получается.
Этот момент и был исправлен, прошу внимательнее посмотреть, а не закрывать вслепую
> fix restrict_chat_member method

- examples/webhook_examples/README.md
There is a small typo in examples/webhook_examples/README.md.
Should read `performance` rather than `perfomance`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, perfomance -> performance

- telebot/handler_backends.py
With argument "password=None" in method __init__(), and argument "password" in "self.redis = Redis(host, port, db, password)", will be able to use Redis with password protection, if password is set .
> Modify RedisHandlerBackend, add argument "password=None" to __init__()

- telebot/apihelper.py
- telebot/version.py
apihelper.SESSION_TIME_TO_LIVE
In seconds.
None - live forever (is it was before, default),
0 - one-time sessions
>0 - time limited sessions
> Added short live sessions

- telebot/apihelper.py
Prevent leaks of the bot token by hiding it from the log, learned it the hard way during https://github.com/eternnoir/pyTelegramBotAPI/issues/1058.
> hide token from debug logs

- README.md
The link is now dead, and so is that bot
> Removed my bot from README

- telebot/__init__.py
For now any exceptions in a middleware handlers are fatal.
This fix will keep TeleBot alive if anything goes wrong. 
Update which caused exception will be skipped.
> middleware handlers exception handling

- telebot/util.py
`user_link` returned an empty string if `include_id` was set to `False`
> Fixed a bug in `user_link`

- telebot/__init__.py
- telebot/types.py
- telebot/util.py
- tests/test_telebot.py
- tests/test_types.py
* Fixed type warnings in some editors by changing `var: Type = None` to `var: Union[Type, None] = None`
* changed some args from `obj['arg']` to `obj.get('arg')` if arg is optional
* better PEP-8 compliance for less weak warnings
* added tests for the new type `ChatInviteLink`
I hope the type warnings are gone for you too
> Some small changes

- .github/workflows/setup_python.yml
To avoid this
that don't show us the version quickly.
> Fix long string blocking version of python on github actions setup

- telebot/types.py
This is a fix for 
```
A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse inline query result: Field "input_message_content" must be of type Object
```
error. It happens when you try to send `InputInvoiceMessageContent` as a part of `InlineQueryResultArticle` query with 
```
bot.answer_inline_query()
```
> 🐛 Bugfix: Add return statement to to_dict() method inside InputInvoiceMessageContent type

- examples/skip_updates_example.py
- telebot/__init__.py
Added skip_updates
It skip old updates except last one.
Added only to polling and infinity polling. Added example too.
As telegram api says in getUpdates method:
The negative offset can be specified to retrieve updates starting from -offset update from the end of the updates queue. All previous updates will forgotten.
I passed negative 1 as offset
Results are shown in images
Before skip updates
After 
As I understood, by passing negative offset will clear all updates except the latest one.
> skip_updates

- telebot/__init__.py
- telebot/apihelper.py
1. Filter optimization: should not store empty filters
2. Filter order: chat_type, content, others
3. Default requests session lifetime set to 600 instead of "forever".
4. Typo fix
> Filter clearance

- README.md
- telebot/apihelper.py
- telebot/util.py
Added apihelper.CUSTOM_REQUEST_SENDER option. It allows to substitute requests.request to your own function.
> Custom request sender

- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- tests/test_types.py
December 7, 2021
Bot API 5.5
Bots are now allowed to contact users who sent a join request to a chat where the bot is an administrator with the can_invite_users administrator right – even if the user never interacted with the bot before.
Added support for mentioning users by their ID in inline keyboards. This will only work in Telegram versions released after December 7, 2021. Older clients will display unsupported message.
Added the methods banChatSenderChat and unbanChatSenderChat for banning and unbanning channel chats in supergroups and channels.
Added the field has_private_forwards to the class Chat for private chats, which can be used to check the possibility of mentioning the user by their ID.
Added the field has_protected_content to the classes Chat and Message.
Added the field …
> Bot API 5.5

- examples/reply_keyboard_markup_example.py
Created a template for QWERTY custom keyboard that can be used by users for their own use cases.
This is an example created using ReplyKeyboardMarkup.
> Create a template for QWERTY custom keyboard an example for ReplyKeyboardMarkup

- telebot/async_telebot.py
Removed redundant logger configuration in `async_telebot.py` that made logs repeated twice. Configuration is already in `__init__.py`.
> Removed redundant logger configuration in async_telebot

- examples/asynchronous_telebot/set_command_example.py
- examples/asynchronous_telebot/timer_bot_async.py
- examples/set_command_example.py
- examples/timer_bot.py
- telebot/__init__.py
- telebot/async_telebot.py
Add default parameters for call bot.get_my_commands() instead bot.get_my_commands(scope=None, language_code=None)
Add examples for [issues #1414  set_my_commands problem](https://github.com/eternnoir/pyTelegramBotAPI/issues/1414 )
> add default None for get_my_commands, examples for bot.set_my_commands

- telebot/__init__.py
In this pull request, additional checks of the message handler decorator inputs are added.
The regexp type is expected to be string. This is checked and a warning message is displayed if necessary.
The commands input types are checked. The commands input is converted to a list of strings and a warning message is displayed if necessary.
> Additional check of the regexp and commands types

- telebot/async_telebot.py
Currently AsyncTelebot does not support async functions as argument for func parameter in handlers.
This pull request allows it to be either sync or async function
> argument of 'func' parameter in handlers can be async function

- telebot/__init__.py
- telebot/async_telebot.py
[CopyMessage](https://core.telegram.org/bots/api#copymessage) returns [MessageId](https://core.telegram.org/bots/api#messageid) while in code it returned `int`
Tests [uses MessageId type already](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/tests/test_telebot.py#L325)
> CopyMessage return type fix

- examples/asynchronous_telebot/formatting_example.py
- examples/formatting_example.py
- telebot/formatting.py
Now, all formatting functions have escape=True by default.
Examples were tested.
OS: MacOs, BigSur
> Set escape=True by default.

- telebot/__init__.py
fix warning
```
WARNING: polling: none_stop parameter is deprecated. Use non_stop instead.
```
when using `infinity_polling `
Python version: 3.9
OS: macos
> fix: warning none_stop parameter is deprecated

- examples/create_invite_link.py
Added create_chat_invite_link() function example
This is an example code on how to create invite links for groups automatically via bot
1 week test using custom bot and a group, works like a charm
Python version: 3.9
OS: Ubuntu 22.04 LTS
> Created create_invite_link.py

- .gitignore
- telebot/__init__.py
- telebot/async_telebot.py
- telebot/util.py
- Fixed send_poll's default explanation parse mode
- Fixed default parse mode in asynctelebot
OS:
> Changed behaviour of default parse mode in sync and async telebot.

- telebot/asyncio_helper.py
Hi, looks like that there is a bug in `asyncio_helper.py`, `get_updates()`, due to which `timeout` parameter is not pass into a `getUpdates` function and as a result, short polling is used instead of a long polling.
> Fixed async long polling

- examples/webhook_examples/webhook_fastapi_echo_bot.py
FastAPI by default includes displaying swagger documentation of its methods. If it is not disabled, then in the above example / dox will see the token in the path for updates.
My edits fix this issue.
All supported versions
OS:
All supported OS
- [ x ] I added/edited example on new feature/change (if exists)
- [ x ] My changes won't break backward compatibility
- [ x ] I made changes both for sync and async
> Fix for token visibility in swagger in fastapi webhook example

- README.md
Update README to include the valid content type 'web_app_data' for Message objects.
That kind of content type is the one that WebApp bots can send from KeyboardButtons, using the sendData method (More info [here](https://core.telegram.org/bots/webapps#initializing-web-apps))
Debug info from TeleBot with the returned message (edited to avoid leaking real data):
DEBUG - TeleBot: "The server returned: 'b'{"ok":true,"result":[{"update_id":000000000,\n"message":{"m
essage_id":000,"from":{"id":00000000,"is_bot":false,"first_name":"XXX","username":"XXX","language_code":"es"},"chat":{"id":00000000,"first_name":"XXX","use
rname":"XXX","type":"private"},"date":1660260000,"web_app_data":{"button_text":"MyWebAppButton","data":"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"}}}]}''"
> Add 'web_app_data' content type to README

- telebot/asyncio_storage/redis_storage.py
aioredis is available in redis-py as of version 4.2.0rc1: https://github.com/aio-libs/aioredis-py#-aioredis-is-now-in-redis-py-420rc1-
Try importing from the new package as well.
I tried async storage with aioredis from redis-py.
OS: Linux
> Import aioredis from redis module too

- telebot/util.py
Other kinds of errors like `Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified` during sending a set of photos or `urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme 127.0.0.1` for forgetting the 'http:\\\\' may occur and should raise exceptions.
> raise other exceptions in antiflood function

- examples/inline_example.py
Fixed InlineQueryResultVideo params in example. String "Video" was passed in stead of the thumbnail url, making the example not work, This has been tested working.
> Fixed InlineQueryResultVideo params in example.

- telebot/__init__.py
- telebot/ext/aio/webhooks.py
- telebot/ext/sync/webhooks.py
`--debug` was removed from uvicorn. See #1767.
Untested; Just removed debug as a param since that was causing `TypeError: run() got an unexpected keyword argument 'debug'` when using `run_webhooks()`.
Python version: 3.9
> fixes: `debug` removed from uvicorn #1767

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 6.3 Update

- telebot/util.py
fixing escape() as replacing a None would throw an exception 'NoneType' object has no attribute 'replace'. useful in case of escaping a None string given from message.from_user.last_name as you dont know wether the user has a last name or not
> fixing escape()

- telebot/async_telebot.py
Fixed super annoying incorrect typehints in register_<any>_handler() methods of AsyncTeleBot
Replaced Awaitable by Callable[[Any], Awaitable]
Defined asynchronous functions with different number of arguments (Any) and different return types
Tried to register them as a handler for AsyncTeleBot - got no warnings for typehints
OS:
> Fixed typehints for register_<any>_handler()

- telebot/__init__.py
- telebot/async_telebot.py
Editing methods allow to pass only inline keyboards as reply markup. Fixed typehints accordingly
OS:
> Fixed typehints for reply markup in editing methods

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 6.4

- telebot/asyncio_storage/pickle_storage.py
- telebot/storage/pickle_storage.py
- telebot/util.py
Fix for issue #1869 
Tried to init StatePickleStorage with Windows-like path. Works fine
OS:
> Make create_dir() method of StatePickleStorage cross-platform instead of POSIX only.

- telebot/util.py
This function can be replaced with this simple code:
```
file_id = None
content_types = ["photo", "video", ...]
for content_type in content_types:
media = getattr(message, content_type)
if media is not None:
file_id = media.file_id
break
```
Thus it can be removed
OS:
> Remove redundant function from util

- telebot/__init__.py
- telebot/async_telebot.py
`bot.edit_chat_invite_link` method contained a mistake: `invite_link` and `name` were supposed to be vice-versa in `apihelper.edit_chat_invite_link(...)` call. This caused to be invite_link empty or contain invalid value, resulting to get `Bad Request: invite link must be non-empty` error.
I swapped `invite_link` and `name` paramteters in `apihelper.edit_chat_invite_link(...)` call.
I tried the following code:
```python
from telebot import TeleBot
TOKEN = "TOKEN"
CHAT_ID = -100123
bot = TeleBot(TOKEN)
info = bot.edit_chat_invite_link(CHAT_ID, bot.create_chat_invite_link(CHAT_ID).invite_link)
print(info)
```
It failed with "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: invite link must be non-empty" error …
> Fix "invite link must be non-empty" error

- telebot/util.py
If we send bot.stop_bot() we will get an exception before the bot is stoped,
because we cannot join current thread
It is trouble only for sync, AsyncTeleBot object has no attribute stop_bot
```
#!/usr/bin/python
import os
import telebot
bot = telebot.TeleBot(os.environ['token'])
@bot.message_handler(commands=['stop'])
def send_stop(message):
bot.reply_to(message, "stop")
bot.stop_bot()
bot.infinity_polling()
```
Python version: 3.8 (may be any)
OS: I check on windows 10 and Ubuntu 22.04.1 LTS
> RuntimeError("cannot join current thread")

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 6.5 update 🔥

- telebot/apihelper.py
- telebot/asyncio_helper.py
No need to pass file content as a header, it causes the http error "431 Request Header Fields Too Large".
> Fix .webm upload

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- tests/test_types.py
> I'm back: Bot API 6.6 Update

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> More changes from review of bot api 6.6 

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- tests/test_types.py
> Bot API 6.7 - Not much to do, just minor improvements

- telebot/async_telebot.py
-fixes #1974
- related commits: c84896391eac80eb08b17d0636999499e921723e f69a2ba044983fbd7b072946df7512d0e2904cd6
the `func` option now can be an async func
it's not going to break any thing but you may want to add a test for it so in the future it could not be deleted again
> bring back the async func message_filter

- telebot/util.py
redesigned the antiflood method for guaranteed message delivery
> redesigned the antiflood method for guaranteed message delivery

- telebot/__init__.py
> Fix typo in docs

- telebot/formatting.py
When I was using backslash in `telebot.formatting.escape_markdown`, I was getting an error from the Telegram API.
The regex pattern inside the `escape_markdown` function was missing a `backslash` within the brackets.
> Fix backslash (\) issue in escape_markdown

- telebot/async_telebot.py
I wanted to increment an error counter whenever the RequestTimeout occurs as an exception via the exception_handler class
Tested on my own project in which I frequently use telebot
Python version: 3.11
OS: Linux Mint
> added posibility to handle exception on RequestTimeout

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 6.8: Stories, voting as a chat, and other minor changes

- telebot/asyncio_storage/redis_storage.py
- telebot/storage/redis_storage.py
Useful for rediss:// and unix:// schemes
OS:
> Add redis_url to StateRedisStorage to allow initialization by URL

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 6.9

- examples/asynchronous_telebot/exception_handler.py
- telebot/__init__.py
- telebot/async_telebot.py
issue https://github.com/eternnoir/pyTelegramBotAPI/issues/2070
Class ExceptionHandler has sync method handle() which is not compatible with async telebot in some cases.
```
export CHAT_ID='' GROUP_ID=''
cd tests
pytest
```
As a result:
2 failed, 106 passed, 2 skipped, 1 warning in 117.93s (0:01:57)
2 failed:
```
FAILED test_telebot.py::TestTeleBot::test_send_file_with_filename - telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: file must be non-empty
FAILED test_telebot.py::TestTeleBot::test_chat_commands - IndexError: list index out of range
```
3.10
OS:
macOS 14.1
> Fix ExceptionHandler handle() method as async for async telebot

- telebot/__init__.py
- telebot/async_telebot.py
Specified the correct return type of the `copy_message` method.
Only documentation was changed, no tests were needed.
> Specified correct return type

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/util.py
- tests/test_handler_backends.py
- tests/test_telebot.py
> Bot API Huge Update - 7.0, introducing reactions, replies and some other changes

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/formatting.py
- telebot/types.py
Separated allow_sending_without_reply and reply_to_message_id into 2 different if-elses for each methods;
Planning to add hcite and mcite
> Changes in deprecated parameters for async

- telebot/types.py
Deprecation stubs for Message fields in InaccessibleMessage to prevent user code exceptions.
Added named parameters in html_text.
> Deprecation: stubs for Message fields in InaccessibleMessage

- telebot/types.py
Fix ChatBoostSource issues
1. "source" is temporary made optional
2. source types are parsed correctly
> Fix ChatBoostSource issues

- telebot/__init__.py
- telebot/async_telebot.py
Fix preview link options if link_preview_options not provided. Get param from class
Tested in my bot project
OS: Windows
> Fix preview link options if link_preview_options not provided

- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
Fix deprecated parameters:
1. Fix descriptions
2. Fix bot.reply_to function
3. Fix ChatPermissions.de_json
> Fix deprecated parameters

- README.md
- telebot/types.py
Added support for the administrator rights can_post_stories, can_edit_stories, can_delete_stories in supergroups.
Added the class [ChatBoostAdded](https://core.telegram.org/bots/api#chatboostadded) and the field boost_added to the class [Message](https://core.telegram.org/bots/api#message) for service messages about a user boosting a chat.
Added the field sender_boost_count to the class [Message](https://core.telegram.org/bots/api#message).
Added the field reply_to_story to the class [Message](https://core.telegram.org/bots/api#message).
Added the fields chat and id to the class [Story](https://core.telegram.org/bots/api#story).
Added the field unrestrict_boost_count to the class [Chat](https://core.telegram.org/bots/api#chat).
Added the field custom_emoji_sticker_set_name to the class …
> Botapi 7.1

- telebot/__init__.py
- telebot/async_telebot.py
Allow to pass no message_id to bot.reply_to
If you want to pass allow_sending_without_reply to bot.reply_to you need to do:
```
reply_parameters = types.ReplyParameters(message.message_id, allow_sending_without_reply=True)
bot.reply_to(query.message, "Some text", reply_parameters=reply_parameters)
```
Where need to pass message.message_id make bot.reply_to a bit useless.
This proposal allows to use it like this:
```
reply_parameters = types.ReplyParameters(None, allow_sending_without_reply=True)
bot.reply_to(query.message, "Some text", reply_parameters=reply_parameters)
```
> Allow to pass no message_id to bot.reply_to

- telebot/custom_filters.py
Fix TextFilter error when no message text and no message caption (for example when processing photo).
Python version: Independent (3.11)
OS: Independent (macOS)
```python
from telebot.custom_filters import TextFilter
@bot.message_handler(
content_types=["photo"],
text=TextFilter(contains=["cat"], ignore_case=True),
)
def handle_cat_photo(message: types.Message):
bot.send_message(
message.chat.id,
"Nice cat!",
)
```
Previously: Python exception:
```
...
File "/home/suren/tg-custom-filters/.venv/lib/python3.11/site-packages/telebot/custom_filters.py", line 162, in check
text = text.lower()
^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```
Now: if photo has no caption, filter returns False
> Fix TextFilter error: if no message text and no caption -> return False

- telebot/apihelper.py
Retry engine 2 behaved differently than retry engine 1.
In particular, POST requests were not retried, because they were not included in the `allowed_methods` parameter of the urllib3 Retry strategy.
Furthermore, requests were retried without delay, ignoring the `RETRY_TIMEOUT` setting, because also the `backoff_` parameters were not implemented in the the urllib3 Retry strategy.
This PR aims to fix these problems, implementing the `allowed_methods`, `backoff_factor` and `backoff_max` parameters in the urllib3 Retry strategy.
It is important to note that `urllib3.util.Retry` does not allow you to directly set a fixed backoff delay, so I set `backoff_factor=RETRY_TIMEOUT` and `backoff_max=RETRY_TIMEOUT`. In this way, already on the second request, the backoff delay exceeds the …
> Retry engine 2 backoff fixes

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/util.py
- tests/test_handler_backends.py
Not promising anything, let's see how far I can go.
Bot API 7.2
Integration with Business Accounts
Working on Behalf of Business Accounts
Information about Business Accounts
Mixed-Format Sticker Packs
Request Chat Improvements
Other Changes
> BOT API 7.2

- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
- Removed the parameter sticker_format from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
Aded handlers to self.typed_middleware_handlers.
Minor deprecation fixes.
> Bot API 7.2 u1

- telebot/formatting.py
Fixed issue in types for Python 3.8
Changed the `dict` to `typing.Dict`
3.11.6
OS:
Windows 10
> Fixed issue in types for Python 3.8

- telebot/apihelper.py
- telebot/asyncio_helper.py
- telebot/types.py
I identified an issue with the outdated function `_convert_entities` used in both the sync and async versions of the `copy_message` method. This function was not functioning correctly, resulting in invalid entities. While all other methods were using a more updated method for converting entities, this particular method was still relying on `_convert_entities`. 
To address this issue, I have removed `_convert_entities` and replaced it with more better `json.dumps(types.MessageEntity.to_list_of_dicts(...))`. This change ensures that the entities are properly converted and are valid
3.12
OS:
windows 10
> Update to resolve Issue with outdated `_convert_entities` function in `copy_message` method

- telebot/__init__.py
- telebot/async_telebot.py
If there is no token in the error, it displays
```
2024-04-26 11:20:41,862 (__init__.py:1091 MainThread) ERROR - TeleBot: "Infinity polling exception: None"
2024-04-26 11:20:41,863 (__init__.py:1093 MainThread) ERROR - TeleBot: "Exception traceback:
None"
```
3.11.6
OS:
Windows 10
> Fixed a bug with hiding the token

- telebot/asyncio_filters.py
Resolves https://github.com/eternnoir/pyTelegramBotAPI/issues/2250
Python version: 3.12.3
OS: Arch Linux
> Add type hints to SimpleCustomFilter

- docs/source/conf.py
- pyproject.toml
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/version.py
> BOT API 7.3

- docs/source/conf.py
- pyproject.toml
- telebot/async_telebot.py
- telebot/version.py
> Bugfix in typing

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/formatting.py
- telebot/types.py
> Bot API 7.4: Stars, effects, etc

- telebot/types.py
Fix missed UsersShared update in BotAPI.
https://core.telegram.org/bots/api#march-31-2024
> Added the class SharedUser and replaced the field user_ids in the class [UsersShared](https://core.telegram.org/bots/api#usersshared) with the field users.
> UsersShared fix

- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 7.5

- .github/workflows/setup_python.yml
Pypy 3.8 removed from tests
Since 7.3.12 they discontinued Pypy 3.8: https://www.pypy.org/posts/2023/06/pypy-v7312-release.html
> Pypy 3.8 removed from tests

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/custom_filters.py
`isinstance()` is working on all python versions.
> fix comparing types

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 7.6

- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Error intervals to stop flooding logs & set non_stop to true by default

- README.md
- telebot/types.py
July 7, 2024
Bot API 7.7
Added the class [RefundedPayment](https://core.telegram.org/bots/api#refundedpayment), containing information about a refunded payment.
Added the field refunded_payment to the class [Message](https://core.telegram.org/bots/api#message), describing a service message about a refunded payment.
other changes are about web apps
@badiboy please release new version afterwards
> bot api 7.7

- telebot/__init__.py
- telebot/async_telebot.py
when we have a custom filter forcing using func is not acceptable in callback_query_handler so i have removed it
OS:
- [*] I added/edited example on new feature/change (if exists)
- [*] My changes won't break backward compatibility
- [*] I made changes both for sync and async
> chg: allow callback_query_handler to do not have func arg.

- telebot/types.py
> Improved typehints for types.py #2351

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot api 7.8

- telebot/__init__.py
- telebot/async_telebot.py
> Use deepcopy instead of a shallow copy for middlewares, #2349

- telebot/__init__.py
- telebot/async_telebot.py
Decided to revert the changes to middlewares.
To change data in handler, the user will need to have a dict parameter, which will obtain original dict, not a shallow copy.
Values are still passed to post_process regardless of handler.
Sorry for the inconvenience.
> Revert changes to middlewares

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 7.9

- telebot/async_telebot.py
fixed order of parameters in `forward_messages` of async telebot
> Fix: Correct order of parameters in forward_messages

- telebot/types.py
Small bug fix, according documentation type should be also `bool` as it is for `request_username` and `request_photo` parameters
Python version: 3.12
OS: macOS
> Fixed typing for `request_name` parameter

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/util.py
- tests/test_handler_backends.py
- tests/test_telebot.py
> bot API 7.10

- examples/asynchronous_telebot/custom_states.py
- examples/custom_states.py
I've replaced the deprecated `reply_to_message_id` with `reply_parameters` in the custom_states examples. I did that after noticing a deprecation message in the logs but couldn't see an example of usage of the new method.
On Telegram I saw this so I used it:
```python
bot.send_message(
<CHAT_ID>,
<TEXT>,
reply_parameters=telebot.types.ReplyParameters(
message_id=<QUOTED_MESSAGE_ID>,
chat_id=<QUOTED_CHAT_ID>,
quote=<QUOTED_TEXT>
)
)
```
I've tested the example code after modification and it seems to have behaved as expected. 
- [ x] I added/edited example on new feature/change (if exists)
- [ x] My changes won't break backward compatibility
- [x ] I made changes both for sync and async
> Replaced deprecated reply_to_message_id with reply_parameters in custom_states examples

- telebot/types.py
Fix KeyboardButtonRequestChat request_title typing from str to bool
no tests needed
Python version: any
OS: any
> Fix KeyboardButtonRequestChat request_title typing

- telebot/types.py
I found that for some deprecations I cannot find where it happens to fix it.
> 2024-10-20 14:41:27,885 (types.py:9267 Thread-12442 (process_request_thread)) WARNING - TeleBot: "Deprecation warning: the filed "from_user" is not accessible for InaccessibleMessage. You should check if your object is Message instance before access."
> 2024-10-20 14:41:27,885 (types.py:9267 Thread-12442 (process_request_thread)) WARNING - TeleBot: "Deprecation warning: the filed "from_user" is not accessible for InaccessibleMessage. You should check if your object is Message instance before access."
> 2024-10-20 14:42:31,599 (types.py:9267 Thread-13476 (process_request_thread)) WARNING - TeleBot: "Deprecation warning: the filed "from_user" is not accessible for InaccessibleMessage. You should check if your …
> Enable call stack logging for deprecation warnings (optional)

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
**Star Subscriptions**
**Full-screen Mode**
**Homescreen Shortcuts**
**Emoji Status**
**Media Sharing and File Downloads**
**Geolocation Access**
**Device Motion Tracking**
**Gifts**
**Loading Screen Customization**
**Hardware-specific Optimizations**
**General**
> Bot API 8.0 - Subscription plans, Emoji Statuses, Gifts and many more

- telebot/formatting.py
The correction ensures that when escape is False, url is used instead of content in the formatted string.
[Issue#2425](https://github.com/eternnoir/pyTelegramBotAPI/issues/2425#issue-2705365214)
```python
from formatting import mlink
print(mlink("content", "http://example.com/test", escape=False))
#[content](http://example.com/test)
print(mlink("content", "http://example.com/test", escape=True))
#[content](http://example\.com/test)
```
3.10
OS:
Windows 11
- [] I added/edited example on new feature/change (if exists)
> Fix: change code for non-escape mode - return url

- README.md
- telebot/types.py
Sorry, I was lazy to separate these into different commits at this point. Here is the changelog anyways:
December 4, 2024
Bot API 8.1
> Bot API 8.1

- telebot/__init__.py
- telebot/async_telebot.py
Fixed method docstring for "subscription_period"
OS: macOS Sonoma 14.7
- Just minor change of param docstring
> Fixed "subscription_period" docstring

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/version.py
> Bot API 8.2 full support

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
> Bot API 8.3 Update

- telebot/formatting.py
- tests/test_telebot.py
Add support for processing code language parameter in `<pre>` tag under message entities
Python version: 3.12
OS: Windows 11
Send a message containing a code block to the bot, then see the result of the parsed HTML code.
> Add support for processing language parameter in message entities

- README.md
- telebot/__init__.py
- telebot/apihelper.py
- telebot/async_telebot.py
- telebot/asyncio_helper.py
- telebot/types.py
- telebot/version.py
April 11, 2025
Bot API 9.0
Business Accounts
Mini Apps
Gifts
Telegram Premium
General
> Bot API 9.0

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/asyncio_storage/base_storage.py
- telebot/states/asyncio/context.py
- telebot/storage/base_storage.py
Fix states functions with new parameters
... and some minor issues.
> Fix states functions with new parameters

- telebot/types.py
**Description:**  
By Telegram specification, thumbnails can be used in the following methods:
- `InputMediaAnimation`
- `InputMediaDocument`
- `InputMediaAudio`
- `InputMediaVideo`
When using **send_media_group**, everything works correctly. For example:
```python
bot.send_media_group(
chat_id=CHAT_ID,
media=[InputMediaAudio(
media=InputFile(file=audio_path), 
thumbnail=InputFile(file=thumbnail_path)
)],
)
```
*Result:*
Audio is successfully sent with a thumbnail.
---
However, currently **edit_message_media** does not support sending thumbnails.
Example with `edit_message_media`:  
```python
initial_message = bot.send_message(CHAT_ID, "Тестовое сообщение.")
bot.edit_message_media(
chat_id=CHAT_ID,
message_id=initial_message.message_id,
media=InputMediaAudio( …
```
> Fix: Add thumbnail support for edit_message_media

- telebot/__init__.py
- telebot/util.py
Fixed type annotations for 3 functions: `edit_message_live_location`, `stop_message_live_location` and `extract_arguments`
Python version: 3.13
OS: Windows
> Fix type annotations

- telebot/__init__.py
- telebot/async_telebot.py
- telebot/types.py
Set func=None as default for the inline handler. and clean up whitespace.
This should not break anything, it falls in line with the way the other handlers are written to default func to None when no filter is required.
3.13
OS:
Ubuntu 24.04
> Default to None for filter func in inline_handler
